[package]
authors = ["woxtu <woxtup@gmail.com>"]
license = "MIT"
name = "httpstat"
version = "0.1.0"

[lib]
name = "httpstat"
path = "src/lib.rs"

[[bin]]
name = "httpstat"
path = "src/main.rs"

[dependencies]
clap = "2.14.0"
curl-sys = "0.4.1"
libc = "0.2.16"
rand = "0.3.14"
regex = "0.1.77"
